### ISSUE TITLE
🥾 emoji bug in _b00t_ asciicast / svg-term

### ISSUE THREAD

**Issue by elasticdotventures** [gaborcsardi/asciicast#26]
I have no idea who to report this to (this seems like a good place to start), but Emoji doesn't preview correctly on the github previews of the asciicast. 

The actual RENDER video on asciinema works fine, just the thumbnail preview shows UTF8 escape sequences for non-western characters (though it seems to show chinese pinyin fine)?

preview:
[http://github.com/elasticdotventures/_b00t_](http://github.com/elasticdotventures/_b00t_)

I will try to debug more on my own, but would appreciate any advice in the proper direction to get this resolved.  Thanks! 

---

Brief description of the problem

[![asciicast](https://asciinema.org/a/QxGcR4JrvSI6ReVi4dhwsYkUP.png)](https://asciinema.org/a/QxGcR4JrvSI6ReVi4dhwsYkUP)

```r
# insert reprex here
```

**Comment by gaborcsardi** [comment]
What's your platform? Do you have an example `.R` file that reproduces this?

**Comment by elasticdotventures** [comment]
I don't understand the relationship between asciicast, asciinema and github.
No, I think the bug is on github markdown thumbnail preview of asciicast.
HOWEVER I suspect the problem is actually in this underlying library, but the code generation is not on my server.

**Comment by gaborcsardi** [comment]
This repository is for an R package, so if you do not use R and the asciicast R package, then I am afraid we cannot help you here.
