### ISSUE TITLE
Control theme/font size in init_knitr_engine

### ISSUE THREAD

**Issue by hadley** [gaborcsardi/asciicast#29]
On https://waldo.r-lib.org, the font size looks a little too small, and the dark theme looks out of place.

**Comment by gaborcsardi** [comment]
Unfortunately this look rather tricky, because AFAICT the font size depends on how wide the image is on the page. So if you set the number of columns in asciicast to a smaller number, you'll probably get a bigger font size.

But I am not sure how we could match the font size to the HTML font size.

**Comment by gaborcsardi** [comment]
@hadley As for the themes, we have SVG themes now, and there is a `github-light` theme, which look appropriate for the waldo pkgdown:

You need to add this after the `init_knitr_engine()` call, in the same chunk:
```r
options(asciicast_theme = "github-light")
```

**Comment by gaborcsardi** [comment]
We could also have an engine that creates HTML instead of an SVG, and then we could use that on pkgdown sites, when we don't need animations.

**Comment by gaborcsardi** [comment]
There is also a "pkgdown" theme now, it looks OK with `asciicast_cols = 80`: https://callr.r-lib.org/articles/r-session.html

(The background color is still slightly different, IDK why. They are literally the same RGB colors. Maybe the SVG has some filter or something.)

In any case, I'll close this now. #33 will be a better solution, once we have that we'll only need SVGs or GIFs for actual animations. And in GH READMEs of course.
