### ISSUE TITLE
Convert to GIF

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/asciicast#3]
Seems complicated. All tools are pretty heavy and need phantom.js, etc.

**Comment by muschellij2** [comment]
See https://github.com/romainfrancois/rsciinema/issues/11, which points to https://github.com/asciinema/asciicast2gif

**Comment by gaborcsardi** [comment]
Fixed in #24. It does need phantom.js, which sucks. But it is pretty hard to improve on this, until we write our own terminal emulator....
