### ISSUE TITLE
accessibility issues in resulting SVGs (unusable in firefox if minimum font size and font size are set)

### ISSUE THREAD

**Issue by masukomi** [gaborcsardi/asciicast#42]
screenshot of readme from firefox with large fonts:

<img width="907" alt="CleanShot 2022-08-04 at 10 19 42@2x" src="https://user-images.githubusercontent.com/2829/182871125-20fcb1e5-e979-44ce-bd4a-f6066e930ebc.png">

This is related to a [known, and thoroughly ignored, firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1677988). 

I've seen this fixed before by running the following against the resulting svg.

```
sed -i '' 's/<text/<text font-size="1.67"/g' doc/screencast.svg
```

You can replicate it by setting your font size to 20 and your _minimum_ font size to 20. 

note: in chrome with large fonts it's visible BUT it's also much smaller than the surrounding text so, may be particularly difficult for people who have trouble with small fonts.

<img width="447" alt="CleanShot 2022-08-04 at 10 24 49@2x" src="https://user-images.githubusercontent.com/2829/182871805-19dbcc95-6966-4178-8188-848ca434f6a8.png">

**Comment by gaborcsardi** [comment]
Hopefully this is fixed in this branch: https://github.com/r-lib/asciicast/tree/fix/firefox-font-size
(You might need to clear the cache in Firefox.)

**Comment by gaborcsardi** [comment]
With #43 merged, the dev pkgdown site should look good for you already: https://r-lib.github.io/asciicast/dev/

**Comment by masukomi** [comment]
lovely. thank you @gaborcsardi
